/**
 * The outage mirror, as nginx configuration. There is no mirror process: nginx
 * serves a pinned episode straight off disk, fills an unpinned one from
 * archive.org through its own cache, and serves the manifest and the magnet
 * links as static files. Two includes, rendered here from one set of
 * parameters so the integration test (test/nginx.test.mjs) runs the exact text
 * production runs, with only the paths and the upstream pointed elsewhere:
 *
 *   http.conf       http level: the cache zone, the connection limit, and the
 *                   "fill" server on a unix socket that turns /mirror/{fileHash}
 *                   into archive.org's /download/{identifier}/{file} and follows
 *                   its 302 to the storage node.
 *   locations.conf  server level, inside the highdesert.space vhost:
 *                   /mirror/manifest, /mirror/magnet/{fileHash}, /mirror/{fileHash}.
 *
 * The allowlist is a directory, not a `map`: `<stateDir>/catalog/<fileHash>`
 * exists for exactly the catalog episodes (it holds the episode's magnet JSON,
 * which is what /mirror/magnet/ serves). A map keyed on 200-byte file hashes
 * needs `map_hash_bucket_size` raised, and that directive cannot be set here:
 * /etc/nginx/conf.d/sogojet-prerender-map.conf declares a map first, which
 * fixes the bucket size, and a later `map_hash_bucket_size` is a "duplicate"
 * error that fails the whole server's config.
 *
 * Why two hops for a fill. The slice module (Range over a cache: each 1 MiB
 * slice is its own cache entry) issues subrequests, and following archive.org's
 * 302 needs an error_page redirect to a named location — which clears the
 * subrequest's slice context, so every slice after the first would go out with
 * no Range. The fill server does the redirect-following without slices, and the
 * outer location does the slicing and caching without redirects.
 */

export const PRODUCTION = Object.freeze({
  stateDir: "/var/lib/highdesert-mirror",
  cacheDir: "/var/cache/highdesert-mirror/proxy",
  fillSocket: "/run/nginx-highdesert-mirror.sock",
  upstream: "https://archive.org",
  // Where archive.org's /download 302 may send us: its storage nodes.
  followPattern: "^https://[a-z0-9-]+(\\.[a-z0-9-]+)*\\.archive\\.org/",
  resolver: "127.0.0.53",
  trustedCa: "/etc/ssl/certs/ca-certificates.crt",
  // 20 GB of filled slices, and never below 10 GB free on the disk (nginx's
  // cache manager evicts least recently used first to hold both).
  maxSize: "20g",
  minFree: "10g",
  slice: "1m",
});

const ident = /^[A-Za-z0-9._\\/:^$()?|+*[\]{}-]+$/;

function check(name, v, re = ident) {
  if (typeof v !== "string" || !re.test(v) || /["';\s]/.test(v)) throw new Error(`nginx: unsafe ${name}: ${v}`);
  return v;
}

export function renderMirrorNginx(opts = {}) {
  const o = { ...PRODUCTION, ...opts };
  const stateDir = check("stateDir", o.stateDir);
  const cacheDir = check("cacheDir", o.cacheDir);
  const sock = check("fillSocket", o.fillSocket);
  const upstream = check("upstream", o.upstream);
  const follow = check("followPattern", o.followPattern);
  const resolver = check("resolver", o.resolver);
  const ca = check("trustedCa", o.trustedCa);
  for (const k of ["maxSize", "minFree", "slice"]) check(k, o[k], /^\d+[kmg]?$/);

  const http = `# Generated by services/mirror/lib/nginx.mjs (scripts/deploy-mirror.sh). Do not edit here.
# The archive.org outage mirror, http level. Included from the highdesert vhost.

# /mirror/ streams whole episodes; an audio element holds one or two
# connections. Six per address is a household, not a crawler walking the
# catalog through our disk.
limit_conn_zone $binary_remote_addr zone=hd_mirror:10m;

# Filled slices of unpinned episodes. The bytes of an archive.org file do not
# change, so an entry is valid for a year; the cache manager evicts least
# recently used first to stay under max_size and above min_free.
proxy_cache_path ${cacheDir} levels=1:2 keys_zone=hd_mirror_cache:16m max_size=${o.maxSize} min_free=${o.minFree} inactive=30d use_temp_path=off;

upstream hd_mirror_fill {
    server unix:${sock};
    keepalive 4;
}

# The fill server: reachable only on the unix socket, only from the location
# below. /mirror/archive:{identifier}:{file} → ${upstream}/download/{identifier}/{file},
# then the one 302 to a storage node. Forwards Range and nothing of the client.
server {
    listen unix:${sock};
    access_log off;

    resolver ${resolver} ipv6=off valid=300s;
    resolver_timeout 5s;

    proxy_http_version 1.1;
    proxy_pass_request_headers off;
    proxy_set_header Range $http_range;
    proxy_set_header Connection "";
    proxy_set_header User-Agent "highdesert.space mirror (+https://highdesert.space)";
    proxy_ssl_server_name on;
    proxy_ssl_verify on;
    proxy_ssl_verify_depth 4;
    proxy_ssl_trusted_certificate ${ca};
    proxy_connect_timeout 5s;
    proxy_send_timeout 15s;
    proxy_read_timeout 15s;
    proxy_buffering off;
    proxy_intercept_errors on;

    location ~ "^/mirror/archive:([^:/]+):([^/]+)$" {
        set $hd_mirror_upstream "${upstream}";
        rewrite "^/mirror/archive:([^:/]+):([^/]+)$" /download/$1/$2 break;
        proxy_pass $hd_mirror_upstream;
        error_page 301 302 303 307 308 = @hd_mirror_follow;
    }

    location @hd_mirror_follow {
        set $hd_mirror_location $upstream_http_location;
        if ($hd_mirror_location !~ "${follow}") {
            return 502;
        }
        proxy_pass $hd_mirror_location;
    }

    location / {
        return 404;
    }
}
`;

  const locations = `# Generated by services/mirror/lib/nginx.mjs (scripts/deploy-mirror.sh). Do not edit here.
# The archive.org outage mirror, server level. Included inside the highdesert.space server.
#
#   /mirror/manifest            ${stateDir}/manifest.json (the warm job writes it)
#   /mirror/magnet/{fileHash}   ${stateDir}/catalog/{fileHash}
#   /mirror/{fileHash}          ${stateDir}/pins/{fileHash} if pinned, else filled
#                               from archive.org through the cache
#
# Nothing here sets add_header, so the server's Strict-Transport-Security is
# inherited; Cache-Control comes from \`expires\`.
location ^~ /mirror/ {
    limit_conn hd_mirror 6;
    limit_conn_status 429;

    location = /mirror/manifest {
        alias ${stateDir}/manifest.json;
        types { }
        default_type application/json;
        expires 60s;
    }

    location ~ "^/mirror/magnet/(?<hd_mirror_mfh>archive:[^/]+)$" {
        root ${stateDir}/catalog;
        types { }
        default_type application/json;
        expires 1d;
        try_files /$hd_mirror_mfh =404;
    }

    location ~ "^/mirror/(?<hd_mirror_fh>archive:[^/]+)$" {
        limit_except GET {
            deny all;
        }
        # The allowlist: catalog episodes only. Anything else never reaches the
        # pin directory or archive.org.
        if (!-f ${stateDir}/catalog/$hd_mirror_fh) {
            return 404;
        }
        root ${stateDir}/pins;
        types { }
        default_type audio/mpeg;
        try_files /$hd_mirror_fh @hd_mirror_fill;
    }

    return 404;
}

# An unpinned episode: 1 MiB slices, each cached on its own, so a seek fetches
# only the slices it needs and a second listener gets them from disk.
location @hd_mirror_fill {
    slice ${o.slice};
    proxy_cache hd_mirror_cache;
    proxy_cache_key $uri$slice_range;
    proxy_cache_valid 200 206 365d;
    proxy_cache_lock on;
    proxy_cache_lock_timeout 20s;
    proxy_ignore_headers Cache-Control Expires Set-Cookie Vary X-Accel-Expires X-Accel-Redirect X-Accel-Limit-Rate X-Accel-Buffering X-Accel-Charset;
    proxy_hide_header Set-Cookie;
    proxy_http_version 1.1;
    # Nothing of the listener goes upstream: no address, no cookie, no agent.
    proxy_pass_request_headers off;
    proxy_set_header Range $slice_range;
    proxy_set_header Connection "";
    proxy_connect_timeout 5s;
    proxy_read_timeout 30s;
    proxy_pass http://hd_mirror_fill;
}
`;
  return { http, locations };
}
